version: "3"

services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: dev
            MYSQL_DATABASE: product
            MYSQL_USER: user
            MYSQL_PASSWORD: password

        volumes: 
            - ./mariadb/init:/docker-entrypoint-initdb.d

    code:
        image: python
        ports:
            - 8080:8080
        command: tail -f /dev/null