version: "3"

services:
    db:
        image: productdb
        restart: always
        container_name: db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: dev
            MYSQL_DATABASE: product
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes: 
            - ./mariadb/init:/docker-entrypoint-initdb.d

    app:
        image: web_app
        container_name: app
        ports:
            - 5000:5000
            - 8080:8080