version: "3"

services:
    db:
        image: productdb
        restart: always
        container_name: db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: dev
            MYSQL_DATABASE: product
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - ./mariadb/init:/docker-entrypoint-initdb.d
            - myvol:/var/lib/mysql/

    app:
        image: web_app
        container_name: app
        restart: always
        ports:
            - 5000:5000
            - 8080:8080
        command: python /app.py
volumes:
    myvol:
        external: true